Solved Issue #21
GalileoSchool/website pull request #22
Opened 2021-08-17 19:57 UTC by AdrianJakubcik

2021-08-23 11:51 UTC, DiscreteConcrete requested changes
this is really dirty. you are doing much more than fixing issue 21. If this was an open source project or if you did this in a company, I would reject the PR. Please don't do this. In other words: a PR should always only do one single thing and not side effects. If you find other things you want to fix, they should be separate PRs, even if it means just one-line PRs. However, this one time I can make an exception - just attend the extra dirty console log comment and please explain what are the other changes you are proposing.

2021-08-23 11:51 UTC, DiscreteConcrete commented on source/js/about.js
> +        //console.log(caller);
?

2021-08-30 17:09 UTC, AdrianJakubcik commented on source/js/about.js
> +        //console.log(caller);
Done

2021-08-30 18:18 UTC, DiscreteConcrete approved these changes

2021-08-30 18:18 UTC, merged